"""init schema

Revision ID: f19f6c77cf65
Revises: 
Create Date: 2026-09-10 11:30:07.712768
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'f19f6c77cf65'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biz_system',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('owner', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('sla_target', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sla_actual', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('ip', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('owner', sa.Text(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topology',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('canvas', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint("jsonb_typeof(canvas) = 'object'", name='ck_topology_canvas'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Text(), nullable=True),
    sa.Column('level', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('acked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_metric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Text(), nullable=False),
    sa.Column('metric', sa.Text(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Double(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topology_node_device',
    sa.Column('topology_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Text(), nullable=False),
    sa.Column('device_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topology_id'], ['topology.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('topology_id', 'node_id'),
    sa.UniqueConstraint('topology_id', 'node_id', name='pk_tnd')
    )
    op.create_index('ix_tnd_device', 'topology_node_device', ['device_id'], unique=False)
    op.create_index('ix_metric_lookup', 'device_metric', ['device_id', 'metric', sa.text('ts DESC')], unique=False)
    op.create_index('ix_alert_newest', 'alert', ['created_at'], unique=False)
    op.create_index('ix_alert_unacked', 'alert', ['level', 'created_at'], unique=False,
                    postgresql_where=sa.text('NOT acked'))
    op.create_index('ux_topology_active', 'topology', ['is_active'], unique=True,
                    postgresql_where=sa.text('is_active'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_topology_active', table_name='topology')
    op.drop_index('ix_alert_unacked', table_name='alert')
    op.drop_index('ix_alert_newest', table_name='alert')
    op.drop_index('ix_metric_lookup', table_name='device_metric')
    op.drop_index('ix_tnd_device', table_name='topology_node_device')
    op.drop_table('topology_node_device')
    op.drop_table('device_metric')
    op.drop_table('alert')
    op.drop_table('topology')
    op.drop_table('device')
    op.drop_table('biz_system')
    # ### end Alembic commands ###
